### PR TITLE
Main elements and styling

### PR DESCRIPTION
**Pull request by flpfar**
This branch contains the following parts that compose the project:
- Every HTML content like texts, links, icons, etc.
- Header with background-image
- Navbar with gradient
- Main elements in a grid
- Footer using floats
- Appropriate readme file

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @flpfar      
#### Great Job so far, but there is one  more thing required. 
## Required Changes:

### Page Structure
#### Navbar
 - [x] There is no Apple logo on the leftmost section of the Navigation bar, lets fix that



### Make changes and submit another code review request.
*Happy coding*

**Comment by flpfar** [comment]
Hey, kobiyoyo! Thanks for reviewing my code!
It seems to me that maybe there is a problem with fontawesome.com in some countries since I've been using the icons from there. As you can see in the screenshot on README file, there actually is an Apple logo there. If you access my project with some VPN, it will probably appear accordingly. Could you reevaluate this, please? Thank you!

**Comment by flpfar** [comment]
I've downgraded the version of fontawesome icons in order to create less incompatibility with DNS.

**Review by kobiyoyo — APPROVED** [review]
### Good job ,Approved

**Pull request merged**
